debug: false
uuid: 20d74a6f-92c6-4159-bcda-aa761b44e5a1
token_id: ETiGTfvqZX1PrkPi
token: I8BoLAztfxkivMVn433TMxr7pMiuaAa3qN9HLP9YPXalwtvZ8JBAePO1iWCFL18j
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: true
    cert: /etc/letsencrypt/live/sg16.avelons.me/fullchain.pem
    key: /etc/letsencrypt/live/sg16.avelons.me/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'https://console.avelons.me'